-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE , sum(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) as SALES from PRODUCT
join OFFLINE_SALE on PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
order by SALES DESC , PRODUCT_CODE asc