# -- 코드를 입력하세요
# SELECT RI.REST_ID ,RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),'2') as SCORE
#     FROM REST_INFO as RI 
#     join REST_REVIEW as RR on RI.REST_ID = RR.REST_ID
#     where RI.address like '서울%' 
#     group by RI.REST_ID ,RI.REST_NAME,RI.FOOD_TYPE,RI.FAVORITES,RI.ADDRESS
#     order by RR.REVIEW_SCORE DESC, RI.FAVORITES DESC
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE
FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC