-- 코드를 입력하세요
SELECT RI.REST_ID ,RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),'2') as SCORE
    FROM REST_INFO as RI 
    join REST_REVIEW as RR on RI.REST_ID = RR.REST_ID
    where RI.address like '서울%' 
    group by RI.REST_ID ,RI.REST_NAME,RI.FOOD_TYPE,RI.FAVORITES,RI.ADDRESS
    order by SCORE DESC, FAVORITES DESC
