-- 코드를 입력하세요
SELECT CAR_RENTAL_COMPANY_CAR.CAR_TYPE , count(*) as CARS from CAR_RENTAL_COMPANY_CAR
where CAR_RENTAL_COMPANY_CAR.OPTIONS like '%시트%'
group by CAR_RENTAL_COMPANY_CAR.CAR_TYPE
order by CAR_RENTAL_COMPANY_CAR.CAR_TYPE ASC