-- 코드를 입력하세요
# SELECT FIRST_HALF.flavor from FIRST_HALF 
#     inner join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
#     where ICECREAM_INFO.INGREDIENT_TYPE='fruit_based' and FIRST_HALF.TOTAL_ORDER > 3000
#     ORDER BY TOTAL_ORDER DESC
SELECT FH.FLAVOR
FROM FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC