-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') FROM USED_GOODS_BOARD as UGB
join USED_GOODS_REPLY as UGR using(BOARD_ID)
where UGB.CREATED_DATE like '%-10-%'
order by UGR.CREATED_DATE ASC, UGB.TITLE ASC
